#pragma once

namespace sentum::dashboard {

inline constexpr const char* kDashboardHtml = R"HTML(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sentum Dashboard</title>
<style>
:root{color-scheme:dark;--bg:#090d14;--panel:#111824;--panel2:#151f2e;--line:#263246;--text:#edf3ff;--muted:#8ea0ba;--good:#46d890;--warn:#f4c95d;--bad:#ff6b72;--accent:#72a7ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif}header{height:64px;display:flex;align-items:center;gap:18px;padding:0 24px;border-bottom:1px solid var(--line);position:sticky;top:0;background:#090d14ee;backdrop-filter:blur(10px);z-index:2}.brand{font-weight:800;font-size:19px;letter-spacing:.08em}.pill{padding:5px 9px;border-radius:999px;background:var(--panel2);color:var(--muted);font-size:12px}.spacer{flex:1}.dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:6px;background:var(--muted)}.good .dot{background:var(--good)}.warn .dot{background:var(--warn)}.bad .dot{background:var(--bad)}main{padding:22px;max-width:1600px;margin:auto}.grid{display:grid;gap:14px}.kpis{grid-template-columns:repeat(6,minmax(130px,1fr));margin-bottom:14px}.two{grid-template-columns:1.3fr 1fr}.card{background:linear-gradient(180deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:12px;padding:16px;min-width:0}.label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.07em}.value{font-size:24px;font-weight:700;margin-top:4px}.section{font-size:15px;font-weight:700;margin-bottom:12px}.health{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.health div{padding:9px;border:1px solid var(--line);border-radius:8px;color:var(--muted)}canvas{width:100%;height:230px;background:#0c121c;border-radius:8px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}th{color:var(--muted);font-weight:600}.scroll{overflow:auto;max-height:330px}.positive{color:var(--good)}.negative{color:var(--bad)}.scanner{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.scan{border:1px solid var(--line);border-radius:8px;padding:10px}.scan b{font-size:15px}.footer{color:var(--muted);padding:16px 0;font-size:12px}@media(max-width:1050px){.kpis{grid-template-columns:repeat(3,1fr)}.two{grid-template-columns:1fr}}@media(max-width:650px){main{padding:12px}.kpis{grid-template-columns:repeat(2,1fr)}header{padding:0 12px}.scanner{grid-template-columns:1fr}}
</style></head>
<body><header><div class="brand">SENTUM</div><div id="mode" class="pill">IDLE</div><div id="health" class="pill">starting</div><div class="spacer"></div><div id="updated" class="pill">connecting…</div></header>
<main>
<div class="grid kpis"><div class="card"><div class="label">Balance</div><div id="balance" class="value">—</div></div><div class="card"><div class="label">Net P&amp;L</div><div id="pnl" class="value">—</div></div><div class="card"><div class="label">Trades</div><div id="trades" class="value">0</div></div><div class="card"><div class="label">Win Rate</div><div id="winrate" class="value">—</div></div><div class="card"><div class="label">Current Symbol</div><div id="symbol" class="value">—</div></div><div class="card"><div class="label">Queue Drop Rate</div><div id="drop" class="value">—</div></div></div>
<div class="grid two"><div class="card"><div class="section">Equity Curve</div><canvas id="equity" width="900" height="230"></canvas></div><div class="card"><div class="section">System Health</div><div id="healthGrid" class="health"></div><div class="section" style="margin-top:16px">Scanner</div><div id="scanner" class="scanner"></div></div></div>
<div class="grid two" style="margin-top:14px"><div class="card"><div class="section">Recent Trades</div><div class="scroll"><table><thead><tr><th>Symbol</th><th>Strategy</th><th>Entry</th><th>Exit</th><th>Net P&amp;L</th><th>Reason</th></tr></thead><tbody id="tradeRows"></tbody></table></div></div><div class="card"><div class="section">Order Events</div><div class="scroll"><table><thead><tr><th>Symbol</th><th>Side</th><th>State</th><th>Executed</th><th>Fill</th><th>Source</th></tr></thead><tbody id="orderRows"></tbody></table></div></div></div>
<div class="card" style="margin-top:14px"><div class="section">Latest Replay / Backtest</div><div id="replay" class="scanner"></div></div>
<div class="card" style="margin-top:14px"><div class="section">Quant Research Leaderboard</div><div id="researchMeta" class="label" style="margin-bottom:10px">No research run available</div><div class="scroll"><table><thead><tr><th>#</th><th>Lookback</th><th>Entry Threshold</th><th>Stop</th><th>Target</th><th>Slippage</th><th>Validation Score</th><th>Overfit Gap</th><th>Validation Trades</th></tr></thead><tbody id="researchRows"></tbody></table></div></div>
<div class="footer">Read-only local dashboard · trading controls intentionally remain outside the browser UI.</div>
</main>
<script>
const $=id=>document.getElementById(id),fmt=(n,d=2)=>Number.isFinite(+n)?(+n).toFixed(d):'—';
async function get(p){try{const r=await fetch(p,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
function draw(points){const c=$('equity'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(!points||points.length<2){x.fillStyle='#8ea0ba';x.fillText('No completed trades yet',20,30);return}const v=points.map(p=>+p.equity),mn=Math.min(...v),mx=Math.max(...v),rg=Math.max(.0001,mx-mn);x.strokeStyle='#72a7ff';x.lineWidth=2;x.beginPath();points.forEach((p,i)=>{const px=i/(points.length-1)*(c.width-30)+15,py=c.height-15-(+p.equity-mn)/rg*(c.height-30);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function healthItem(name,val){const cls=val===true?'good':val===false?'bad':'warn';return `<div class="${cls}"><span class="dot"></span>${name}: ${val===true?'OK':val===false?'DOWN':String(val??'n/a')}</div>`}
async function refresh(){const [s,t,o,e,r,q]=await Promise.all([get('/api/status'),get('/api/trades?limit=100'),get('/api/orders?limit=100'),get('/api/equity?limit=500'),get('/api/replay'),get('/api/research')]);if(!s)return;
$('mode').textContent=String(s.mode||'idle').toUpperCase();$('health').textContent=s.health||'unknown';$('updated').textContent=new Date().toLocaleTimeString();$('balance').textContent=fmt(s.balance,2)+(s.quote_asset?' '+s.quote_asset:'');$('pnl').textContent=fmt(s.total_profit,2);$('pnl').className='value '+((+s.total_profit||0)>=0?'positive':'negative');$('trades').textContent=s.total_trades||0;$('winrate').textContent=fmt(s.win_rate,1)+'%';$('symbol').textContent=s.current_symbol||s.symbol||'—';$('drop').textContent=fmt((+s.drop_rate||0)*100,3)+'%';
$('healthGrid').innerHTML=healthItem('Market data',s.market_data_connected)+healthItem('User stream',s.user_stream_connected)+healthItem('Reconciled',s.reconciliation_complete)+healthItem('Kill switch',s.kill_switch_active?false:true)+healthItem('Collector',s.collector_active)+healthItem('Scanner',s.scanner_active);
$('scanner').innerHTML=(s.scanner||[]).map(v=>`<div class="scan"><b>${v.symbol||'—'}</b><div class="${(+v.return||0)>=0?'positive':'negative'}">${fmt((+v.return||0)*100,2)}%</div></div>`).join('')||'<span class="label">No ranking data</span>';
$('tradeRows').innerHTML=(t||[]).map(v=>`<tr><td>${v.symbol||''}</td><td>${v.strategy||''}</td><td>${fmt(v.entry_price,4)}</td><td>${fmt(v.exit_price,4)}</td><td class="${(+v.net_profit||0)>=0?'positive':'negative'}">${fmt(v.net_profit,2)}</td><td>${v.exit_reason||''}</td></tr>`).join('');
$('orderRows').innerHTML=(o||[]).map(v=>`<tr><td>${v.symbol||''}</td><td>${v.side||''}</td><td>${v.state||''}</td><td>${fmt(v.executed_quantity,6)}</td><td>${fmt(v.average_fill_price,4)}</td><td>${v.source||''}</td></tr>`).join('');draw(e||[]);
const keys=['net_profit','max_drawdown','profit_factor','win_rate','sharpe','sortino'];$('replay').innerHTML=keys.map(k=>`<div class="scan"><span class="label">${k.replaceAll('_',' ')}</span><div><b>${fmt(r?.[k],3)}</b></div></div>`).join('');
const lb=q?.leaderboard||[];$('researchMeta').textContent=q?.symbol?`${q.symbol} · objective ${q.objective} · ${q.trials||0} trials · ${q.folds||0} folds`:'No research run available';$('researchRows').innerHTML=lb.slice(0,10).map((v,i)=>`<tr><td>${i+1}</td><td>${v.parameters?.lookback??''}</td><td>${fmt(v.parameters?.entry_threshold,6)}</td><td>${fmt(v.parameters?.stop_loss_percent,4)}</td><td>${fmt(v.parameters?.take_profit_percent,4)}</td><td>${fmt(v.parameters?.slippage_percent,5)}</td><td><b>${fmt(v.validation_score,5)}</b></td><td class="${Math.abs(+v.overfit_gap||0)<.5?'positive':'negative'}">${fmt(v.overfit_gap,5)}</td><td>${v.validation?.trades??0}</td></tr>`).join('')}
refresh();setInterval(refresh,2000);
</script></body></html>)HTML";

} // namespace sentum::dashboard
